In [13]:
import numpy as np

temperaturas = np.array([
    [12, 20],
    [14, 22],
    [10, 18],
    [15, 24],
    [13, 19]
]) 

precios = np.array([12.5, 8.0, 25.0, 5.5])
unidades_vendidas = np.array([10, 25, 4, 60])

# 1. Forma del array
print("Forma:", temperaturas.shape)

# 2. Temperatura media de cada día
media_dias = temperaturas.mean(axis=1)
print("Media de cada día:", media_dias)

# 3. Temperatura media de cada franja horaria
media_horas = temperaturas.mean(axis=0)
print("Media a las 9h y 18h:", media_horas)

# 4. Días en los que a las 18h superó los 20 ºC
mascara_binaria = temperaturas[:, 1] > 20
print('Máscara Binaria', mascara_binaria)
dias = temperaturas[mascara_binaria]
print("Días con más de 20 ºC a las 18h:", dias)

Forma: (5, 2)
Media de cada día: [16.  18.  14.  19.5 16. ]
Media a las 9h y 18h: [12.8 20.6]
Máscara Binaria [False  True False  True False]
Días con más de 20 ºC a las 18h: [[14 22]
 [15 24]]


In [8]:


import numpy as np

precios = np.array([12.5, 8.0, 25.0, 5.5])
unidades_vendidas = np.array([10, 25, 4, 60])

# 1. Ingresos por producto
ingresos = precios * unidades_vendidas
print("Ingresos por producto:", ingresos)

# 2. Ingreso total
ingreso_total = np.sum(ingresos)
print("Ingreso total:", ingreso_total)

# 3. Productos que generaron más de 100 €
mas_de_100 = ingresos > 100
print("Productos con más de 100 €:", mas_de_100)
print("Ingresos superiores a 100 €:", ingresos[mas_de_100])

# 4. Descuento del 10% a todos los precios
precios_rebajados = precios * 0.90
print("Precios rebajados:", precios_rebajados)

Ingresos por producto: [125. 200. 100. 330.]
Ingreso total: 755.0
Productos con más de 100 €: [ True  True False  True]
Ingresos superiores a 100 €: [125. 200. 330.]
Precios rebajados: [11.25  7.2  22.5   4.95]


In [17]:
import numpy as np

tablero = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 1. Segunda fila completa (índice 1)
segunda_fila = tablero[1]
print(segunda_fila)

# 2. Tercera columna completa (índice 2)
tercera_columna = tablero[:, 1]
print("2. Tercera columna completa (índice 2):",tercera_columna)

# 3. Submatriz 2x2 de la esquina inferior derecha
submatriz = tablero[2:4, 2:4]
print("# 3. Submatriz 2x2 de la esquina inferior derecha:\n",submatriz)

# 4. Suma total de todos los valores
suma_total = tablero.sum()
print(suma_total)



[5 6 7 8]
2. Tercera columna completa (índice 2): [ 2  6 10 14]
# 3. Submatriz 2x2 de la esquina inferior derecha:
 [[11 12]
 [15 16]]
136


In [18]:
import numpy as np

fuerza_1 = np.array([3, 4])
fuerza_2 = np.array([-1, 2])

# 1. Fuerza resultante
fuerza_resultante = fuerza_1 + fuerza_2
print("Fuerza resultante:", fuerza_resultante)

# 2. Magnitud de cada fuerza
magnitud_fuerza_1 = np.linalg.norm(fuerza_1)
magnitud_fuerza_2 = np.linalg.norm(fuerza_2)

print("Magnitud fuerza_1:", magnitud_fuerza_1)
print("Magnitud fuerza_2:", magnitud_fuerza_2)

# 3. Magnitud de la fuerza resultante
magnitud_resultante = np.linalg.norm(fuerza_resultante)
print("Magnitud resultante:", magnitud_resultante)

# 4. Comprobar cuál es mayor
print("¿fuerza_1 es mayor que fuerza_2?:", magnitud_fuerza_2 > magnitud_fuerza_1)

Fuerza resultante: [2 6]
Magnitud fuerza_1: 5.0
Magnitud fuerza_2: 2.23606797749979
Magnitud resultante: 6.324555320336759
¿fuerza_1 es mayor que fuerza_2?: False


In [11]:
import numpy as np

M = np.array([
    [2, 0, 1],
    [1, 3, 2],
    [0, 1, 4]
])

# 1. Transpuesta de M
MT = M.T
print("1. Transpuesta de M:")
print(MT)

# 2. Producto matricial M · M.T
producto = M @ MT
print("\n2. M @ M.T:")
print(producto)

# 3. Inversa de M
inversa = np.linalg.inv(M)
print("\n3. Inversa de M:")
print(inversa)

# 4. Comprobar que M · M⁻¹ es la identidad
comprobacion = np.round(M @ inversa)
print("\n4. M @ M⁻¹:")
print(comprobacion)

1. Transpuesta de M:
[[2 1 0]
 [0 3 1]
 [1 2 4]]

2. M @ M.T:
[[ 5  4  4]
 [ 4 14 11]
 [ 4 11 17]]

3. Inversa de M:
[[ 0.47619048  0.04761905 -0.14285714]
 [-0.19047619  0.38095238 -0.14285714]
 [ 0.04761905 -0.0952381   0.28571429]]

4. M @ M⁻¹:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
