In [1]:
import numpy as np

temperaturas = np.array([
    [12, 20],
    [14, 22],
    [10, 18],
    [15, 24],
    [13, 19]
])

# 1. Forma del array
print(temperaturas.shape)

# 2. Temperatura media de cada día
media_dias = temperaturas.mean(axis=1)
print(media_dias)

# 3. Temperatura media de cada franja horaria
media_horas = temperaturas.mean(axis=0)
print(media_horas)

# 4. Días en los que la temperatura de las 18h supera los 20ºC
dias = temperaturas[:, 1] > 20
print(dias)

(5, 2)
[16.  18.  14.  19.5 16. ]
[12.8 20.6]
[False  True False  True False]


In [2]:
precios = np.array([12.5, 8.0, 25.0, 5.5])
unidades_vendidas = np.array([10, 25, 4, 60])

# 1. Ingresos por producto
ingresos = precios * unidades_vendidas
print(ingresos)

# 2. Ingreso total
total = ingresos.sum()
print(total)

# 3. Productos que generaron más de 100€ de ingresos
productos_mas_100 = ingresos > 100
print(productos_mas_100)

# 4. Descuento del 10% en los precios
precios_rebajados = precios * 0.90
print(precios_rebajados)

[125. 200. 100. 330.]
755.0
[ True  True False  True]
[11.25  7.2  22.5   4.95]


In [3]:
tablero = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 1. Segunda fila completa
print(tablero[1, :])

# 2. Tercera columna completa
print(tablero[:, 2])

# 3. Submatriz 2x2 de la esquina inferior derecha
print(tablero[2:4, 2:4])

# 4. Suma de todos los valores
print(tablero.sum())

[5 6 7 8]
[ 3  7 11 15]
[[11 12]
 [15 16]]
136


In [4]:
# Inicialización de vectores
fuerza_1 = np.array([3, 4])
fuerza_2 = np.array([-1, 2])

# 1. Calcula la fuerza resultante sumando ambos vectores
fuerza_resultante = fuerza_1 + fuerza_2
print("1. Fuerza resultante:", fuerza_resultante)  # Resultado: [2, 6]

# 2. Calcula la magnitud (norma euclidiana) de cada fuerza por separado
mag_f1 = np.linalg.norm(fuerza_1)
mag_f2 = np.linalg.norm(fuerza_2)
print(f"2. Magnitud fuerza_1: {mag_f1}, Magnitud fuerza_2: {mag_f2:.2f}")  # f1 dará: 5.0

# 3. Calcula la magnitud de la fuerza resultante obtenida en el paso 1
mag_resultante = np.linalg.norm(fuerza_resultante)
print(f"3. Magnitud de la fuerza resultante: {mag_resultante:.2f}")  # Resultado aprox: 6.32

# 4. Comprueba si la magnitud de fuerza_1 es mayor que la de fuerza_2
comparacion = mag_f1 > mag_f2
print("4. ¿fuerza_1 es mayor que fuerza_2?:", comparacion)  # Resultado: True

1. Fuerza resultante: [2 6]
2. Magnitud fuerza_1: 5.0, Magnitud fuerza_2: 2.24
3. Magnitud de la fuerza resultante: 6.32
4. ¿fuerza_1 es mayor que fuerza_2?: True


In [5]:
# Inicialización de la matriz
M = np.array([
    [2, 0, 1],
    [1, 3, 2],
    [0, 1, 4]
])

# 1. Calcula la transpuesta de M
M_T = M.T
print("1. Transpuesta de M:\n", M_T)

# 2. Calcula el producto matricial de M por su transpuesta (M @ M.T)
producto_matricial = M @ M_T
print("\n2. Producto matricial M @ M.T:\n", producto_matricial)

# 3. Calcula la inversa de M con np.linalg.inv()
M_inv = np.linalg.inv(M)
print("\n3. Inversa de M:\n", M_inv)

# 4. Comprueba que M multiplicada por su inversa da (aproximadamente) la matriz identidad
matriz_identidad = np.round(M @ M_inv)
print("\n4. Comprobación (Matriz Identidad):\n", matriz_identidad)

1. Transpuesta de M:
 [[2 1 0]
 [0 3 1]
 [1 2 4]]

2. Producto matricial M @ M.T:
 [[ 5  4  4]
 [ 4 14 11]
 [ 4 11 17]]

3. Inversa de M:
 [[ 0.47619048  0.04761905 -0.14285714]
 [-0.19047619  0.38095238 -0.14285714]
 [ 0.04761905 -0.0952381   0.28571429]]

4. Comprobación (Matriz Identidad):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
